containers/aardvark-dns

.cirrus.yml
Makefile
OWNERS
src/config/mod.rs
src/main.rs

initial ci setup for aardvark.  we simply check dco, run tests (of which
there are none yet), and run the formatter.

add basic ci setup

---

src/test/config/podman
src/test/config/test1

Add test configurations for Aardvark

---

src/server/serve.rs

Aardvark config can contain list of both `IPv4` and `IPv6`.
Following PR ensures that we spin servers for `IPv6` as well
without ignoring.

server: spin servers for `IPv6` dynamically from config

---

.cirrus.yml

Cirrus: Switch to using VMs for automation

---

src/dns/coredns.rs

By default aardvark forwards request to configured resolver, but in
testing scenarios no host env is available so allow users to bypass
proxy if they need to.
if env contains `AARDVARK_NO_PROXY=true` aardvark returns `NXDOMAIN` if no entry is found in
DNSBackend instead of forwarding it to configured resolver.

coredns: skip proxy if `AARDVARK_NO_PROXY` is found and return `NXDOMAIN`

---

Cargo.toml
README.md
RELEASE_NOTES.md

Bump to v1.0.0-rc1

---

.cirrus.yml
Cargo.lock
Makefile
test/100-basic-name-resolution.bats
test/200-two-networks.bats
test/300-three-networks.bats
test/400-aliases.bats
test/500-reverse-lookups.bats
test/helpers.bash

Initial set of tests for aardvark and wire it up to CI.

Add bats tests for aardvark

---

test/300-three-networks.bats

cleaning some left over debug and a typo.

small tests cleanup

---

src/server/serve.rs

Never stop core server is any thread under the hood panics.

server: remove any direct panics from server

---

src/backend/mod.rs
src/config/mod.rs
src/server/serve.rs
test/helpers.bash

Removes some last remaining bits of unwrap usage
Edit: Although all the necessary unwrap were removed before but this makes sure we don't have any unwrap traces at all.
This completely closes the issue: https://github.com/containers/aardvark-dns/issues/59

server, config: remove all remaining unwraps

---

DISTRO_PACKAGE.md

@baude @Luap99 @mheon @flouthoc @TomSweeneyRedHat @rhatdan PTAL. I thought I sent this one already, but evidently not.

DISTRO_PACKAGE.md: info for packagers and package users

---

test/200-two-networks.bats
test/300-three-networks.bats
test/helpers.bash

Run a formatter against the bats files, there is no problem with the
current version but I think this looks a bit better.

format bats test files

---

src/backend/mod.rs
src/commands/run.rs
src/config/mod.rs
src/dns/coredns.rs
src/main.rs
src/server/serve.rs

Make `cargo clippy` happy and remove unwanted code.

cleanup: perform cleanups for clippy

---

.cirrus.yml

Add Fedora 36 native rust build check

---

RELEASE_NOTES.md

release notes for v1.0.2

---

src/server/serve.rs

We are wasting CPU cycles while notifying servers whenever aardvark
performs a refresh, we don't need to do that anymore after we switched
to mpmc ( multi-producer, multi-consumer ) design for notification here
: https://github.com/containers/aardvark-dns/pull/48

server, performance: no need to notify individual servers by making extra `UDP` connection.

---

src/config/mod.rs

fix: dedup network names

---

Cargo.lock
Cargo.toml
RELEASE_NOTES.md

* Updated dependency libraries
* Reduction in CPU use
* Fixed bug with duplicate network names

V1.0.3 release

---

Cargo.toml

Update `cargo.toml` with fields necessary for packaging.

cargo.toml: update info fields for packaging

---

.cirrus.yml
contrib/cirrus/runner.sh
contrib/cirrus/setup.sh

Cirrus: enable Fedora 36 aarch64 tasks on EC2

---

src/backend/mod.rs

Follow clippy standards and remove needless borrow.
Ref: https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

backend,clippy: remove needless borrow from lookup logic

---

Makefile

This tool creates a much small vendor dir since we can only include the linux dependencies. Our current one on main is over 70 MB big and with cargo vendor-filterer it is only 6 MB.
see https://github.com/coreos/cargo-vendor-filterer

 use cargo-vendor-filterer to create vendor tarball

---

Cargo.lock
Cargo.toml

Fix dev version

---

README.md

silly pr to fix ci

---

.cirrus.yml
src/server/serve.rs

ref https://github.com/containers/automation_images/pull/241

update CI images

---

contrib/cirrus/setup.sh

Fixes: https://github.com/containers/aardvark-dns/pull/267
See also: https://github.com/containers/netavark/pull/520
Around the time of this commit, a bug was discovered (the hard way) in Cirrus-CI:  If a `[skip-ci]` build merges, it will be marked successful but not publish any artifacts via the "latest" permalink. Since netavark and aardvark depend on each other's latest binaries, this can lead to a chicken-and-egg problem.
While the underlying Cirrus-CI bug has now been fixed, this is still a fragile situation for CI.  At the same time, it's beneficial to developers for CI runs to happen as quickly as possible.  Meaning, CI should try to avoid compiling when possible.
Resolve both issues by attempting to download from the permalink, but if that fails, fallback to compiling and building …

Cirrus: Add backup to netavark-binary artifact DL

---

CODE-OF-CONDUCT.md

Like the other repositories this repo follow the containers code of conduct, add a link in this repo to make that clear.
Fixes #279

add code of conduct

---

Cargo.lock
Cargo.toml
RELEASE_NOTES.md

* dependency updates
* code of conduct added

Releasev1.5.0

---

.packit.sh
Cargo.toml

@Luap99 @edsantiago @cevich PTAL

[CI:DOCS] Clarify packit related comments

---

.cirrus.yml
contrib/cirrus/netavark_cache_groom.sh

Depends on https://github.com/containers/netavark/pull/559
Port of https://github.com/containers/netavark/pull/553

Cirrus: Groom rust cache before updating

---

.github/dependabot.yml

Disable Dependabot in favor of Renovate

---

rpm/aardvark-dns.spec

- remove unnecessary conditionals
- fix ELN builds on copr environments
Note: The ELN build fix is actually handled on the COPR side by enabling the `local` repo. It's usually disabled by default on copr and enabled by default on koji, sometimes leading to inconsistent results.

[CI:BUILD] RPM: cleanup spec and fix eln builds

---

.packit.yaml

[CI:BUILD] Packit: tag @lsm5 on copr build failures

---

.packit.yaml

Packit: switch to @containers/packit-build team for copr failure notification comments

---

src/main.rs

Never report an error when the syslog init fails, there are systems without syslog (e.g. inside containers) and we should not spam a random expected messages in this context.
Also add aardvark-dns to the error context as this is printed to stderr which is inherited from the podman command so it is not clear which process wrote it otherwise.
Fixes https://github.com/containers/podman/issues/19809

aardvark main: change error reporting

---

test/helpers.bash

The test setup was wrong, choosing a ip randomly had the result that sometimes two containers ended up with the same ip which resulted in aardvark-dns returning a wrong response.
To fix this lets make sure to not assing the same ip more than once by using a counter.
Fixes #411

fix duplicated IP CI flake

---

Cargo.lock
Cargo.toml
build.rs

requires working around two deprecations; small change needed

update chrono package

---

Cargo.lock
Cargo.toml
src/commands/run.rs

nix changed some of its api signatures. small tweaks required

Update to nix-0.28.0

---

.packit.yaml

[skip-ci] Packit: Remove EL8 jobs

---

src/backend/mod.rs
src/config/mod.rs
src/dns/coredns.rs
src/server/serve.rs
src/test/test.rs
test/300-three-networks.bats

Should make the code readable and also contains a bug fix.
see commits
This is just a tiny part. I will restructure much more code on top of this but wanted to push in smaller steps for review.

rework parts of coredns code

---

src/dns/coredns.rs
src/server/serve.rs

This got a bit out of hand but I think the end result is much easier to understand and reason about.
see commits for details, it might be easier to just read the final coredns file for review rather than trying to make sense of the diff as a lot of code was moved around

rework parts of coredns and server code part 2

---

src/dns/coredns.rs
src/main.rs
src/server/serve.rs

More rework and cleanups to get closer to the place where we can report bind errors

---

rpm/gating.yaml

[skip-ci] RPM: fix gating.yaml

---

Cargo.lock
Cargo.toml
src/backend/mod.rs
src/dns/coredns.rs

Includes two minor changes that are now reported by clippy.

update log to 0.4.27

---

Cargo.lock
Cargo.toml
src/dns/coredns.rs

Includes fixes for several breaking changes and the update contains my fix for #473.
Fixes #473

update hickory to 0.25.1

---

.github/workflows/release.yml

Copied from netavark, minus the protobuf install as it is not needed here.

github: add automatic release action
