- src/commands/run.rs
- src/lib.rs
- src/main.rs
- src/server/mod.rs
- src/server/serve.rs
Implement `aardvark-dns --file <config> run` to actually parse and run server
> run: hook server which can parse `DNSbackend` and `listen ips`

- src/dns/coredns.rs
We need dns server to be able to understand `underscore` in record
names. So fallback to `utf8` if `IDNA` fails and try using record name
anyhow.
References:
https://datatracker.ietf.org/doc/html/rfc952
https://www.iana.org/assignments/idna-tables-6.3.0/idna-tables-6.3.0.xhtml
https://datatracker.ietf.org/doc/html/rfc5890#section-2.3.1
> dns: allow `underscore` in record origin, fallback to `utf8` instead of `IDNA` parsing

- src/dns/coredns.rs
- src/server/serve.rs
Configure coredns to use lookup logic directly from `DNSBackend` instead
of using `Authority` records.
This prevents creating copies of `A/AAAA` record entries and we follow
desired logic for lookup.
> dns: hook `DNSBackend` for `A/AAAA` records lookup instead of using `Authority` records

- src/dns/coredns.rs
- src/server/serve.rs
* Listen dynamically for each network in a different thread
* Share backend via `Arc` across threads to prevent memory duplication
> server,dns: dynamically spawn servers via threads for each listener and implement `Arc` for `DNSBackend`

- src/backend/mod.rs
- src/server/serve.rs
Backend must treat fully qualified domain names as regular entries,
since container names don't following qualified domain names but we get
them as fully qualified domain names which is not applicable for backend.
> backend: resolve fully qualified domain names ( `FQDN` ) as regular container entries

- src/config/constants.rs
- src/config/mod.rs
- src/server/serve.rs
Other process send Signals to aardvark's process hence they need access
to aardvark's `pid`. Therefore on every run aardvark will create `pid`
files on the specified config.
If aardvark ever crash and restarts it will automatically update its `pid` file with
new `pid`.
> config, server: generate aardvark `pid` files for interprocess signaling

- src/server/serve.rs
Lets not run aardvark as a daemon.
> server, daemon: Kill server when not needed and make it `daemonless`.

- aardvark-dns.spec.rpkg
@flouthoc @baude @mheon @Luap99 PTAL. Trivial fix to make sure rpm doesn't show weird info.
> Fix the rpm summary in copr template

- .cirrus.yml
As a minor, readability improvement, rearrange tasks in sequence order.
Also ensure the "validate" task is a dependency of "success".
To help support downstream testing with a rapidly evolving aardvark and
netavark, make the compiled and tested binary available for download.
In the future this should be replaced by use of packaged binaries,
pre-installed into the test VM.
> Cirrus: Rearrange tasks + upload binary artifacts

- .autocopr/aardvark-dns.spec
This should be gotten rid of once the copr infra upgrade to f35 is
complete in favor of aardvark-dns.spec.rpkg.
@mheon @baude @rhatdan PTAL.
> copr workaround: temporarily re-add .autocopr/aardvark-dns.spec

- Makefile
This would imply `make && make install` for people building from source.
It would also save the Makefile from getting polluted with `-nobuild`
targets.
@flouthoc @baude @mheon @Luap99 @rhatdan PTAL.
> Makefile: install target shouldn't call build

- src/server/serve.rs
Rust closes the fd only when it leaves the scope, since this is
the main loop it will never happen so we have to manually close it.
Also we should not leak the pid file on exit.
> Fix leaking pid file fd and remove pid file on exit 

- src/dns/coredns.rs
It seems we don't set QR bit to `1` for dns response lets do that.
> coredns: set `QR` to `1` bit for response messages

- src/server/serve.rs
Hotfix: Just rely on kill switch and don't wait for child threads.
> server, hotfix: stop holding child threads as they are not relevent

- Makefile
- src/dns/coredns.rs
- src/server/serve.rs
Why ?
It seems there is a race if interface is removed from below before we stop event loop and closing
sockets won't stop the event loop. So lets de-couple thread killing from any network code.
Solution:
Receiver is already async so leverage that and move kill_switch to an
event loop which is not dependent on receiver.
Following solution makes sure that our thread management is not
dependent on any networking code. If we want to kill the thread we can
kill it.
> dns, server: don't trigger kill_switch inside receiver block instead move it to parent `event loop`.

- src/commands/run.rs
- src/dns/coredns.rs
- src/main.rs
- src/server/serve.rs
We did a workaround in dnsname/dnsmasq setup to append a default
search-domain to all dns queries. Lets support that.
By default it filter's out `dns.podman`
> dns: add support to whiteout search-domain, defaults for `.dns.podman`

- .cirrus.yml
Port of https://github.com/containers/netavark/pull/191 for identical
purpose.
> Cirrus: Identify precisely where binary came from

- src/dns/coredns.rs
If request is for internal entry and we dont have internal entry
return `NXDOMAIN`.
> dns: return `NXDOMAIN` if request was for internal entry and entry is not there.

- test/200-two-networks.bats
when dig'ing at a host that should not resolve, we now also check with
the host command to make sure we get a NXDOMAIN response.
> check for nxdomain

- src/backend/mod.rs
dns: Return fully borrowed value
This is even simpler and more efficient.
---
dns: Use triple slash function documentation
A bit better best practice.
---
dns: Use `filter_map` to lower nesting
Combinators versus explicit matching can be a bit of a taste thing;
in this case I find `filter_map()` avoids nesting and makes things
a bit clearer.
---
> dns: A few minor patches

- .cirrus.yml
- contrib/cirrus/lib.sh
- contrib/cirrus/runner.sh
- contrib/cirrus/setup.sh
- hack/get_ci_vm.sh
- src/config/mod.rs
This necessitated porting `setup.sh` and `runner.sh` over from the
Netavark repo.  While I dislike duplicating the code, there are some
subtle differences.  Otherwise, a large portion is boiler-plate which
is needed to facilitate corresponding experiences in CI and get_ci_vm.sh
> Cirrus: Add get_ci_vm.sh support

- Makefile
- test/100-basic-name-resolution.bats
- test/helpers.bash
To test upstream resolvers we need a connection to the internet. We can
use slirp4netns for this. Also create a new mount namespace so that we
can bind mount a correct resolv.conf which points to the slirp4netns
resolver.
> tests: add slirp4netns to connect the host netns

- test/100-basic-name-resolution.bats
- test/200-two-networks.bats
- test/helpers.bash
When we create a new netns with unshare we have to wait until it
completes before using the ns. When we run things in the background with
`&` we always need to check that the process is ready before using it.
We now have ready checks for unshare and slirp4netns so it should no
longer flake even on slow systems.
Also only setup slirp4netns when needed for the test to safe some setup
time.
> tests: fix slirp flake

- .cirrus.yml
make validate cannot complete with errors is now being enforced.
> Make validate must not error

- .cargo/config.toml
- .gitignore
- DISTRO_PACKAGE.md
- contrib/cirrus/runner.sh
We should not try to build with deps from the vendor directory locally.
This will force me to run make vendor manually if I pull in new deps.
When distros want to build with bundlwd deps they should a) download
the linked vendor tarball which we should provide for the releases and
b) create the cargo config since to let cargo use the vendor dir.
```
tar xvf %{SOURCE1}
mkdir -p .cargo
cat >.cargo/config << EOF
[source.crates-io]
replace-with = "vendored-sources"
[source.vendored-sources]
directory = "vendor"
EOF
```
see https://src.fedoraproject.org/rpms/rust-coreos-installer/blob/rawhide/f/rust-coreos-installer.spec#_86
Signed-off-by: Paul Holzinger <pholzing@redhat.com>
> use local cargo dependencies

- Cargo.lock
- Cargo.toml
- RELEASE_NOTES.md
- update release notes
- cut release v1.0.1
- bump to 1.0.2-dev
> aardvark-dns-v1.0.1

- .cirrus.yml
- Cargo.lock
- Cargo.toml
- build.rs
- src/commands/version.rs
- src/main.rs
Backport commit e824402c85d7.
We only need the version, build time, rust target triple, and git commit
for the version command. These values can easily be generated with little
code so we do not need an extra dependency for this.
The main reason for this change is that vergen will fail if no git
commit is found. On distro build systems this is often the case since
they build from a source tar without the git repo. Instead of erroring
we should just show an empty commit in the version output.
> [v1.0.1-rhel] Backport "Drop vergen dependency"

- test/helpers.bash
Commit 4a451679ebbe points at the correct error source however the fix
for it was not working. ls -l will always look different when called on
different paths. We only want to compare the actual link target. Fix
this by using readlink.
Fixes #110
> tests: fix slirp flake v2

- test/helpers.bash
Right now assert t:[1] != t:[1] passes. This is obviously incorrect
and some test might not be working correctly because of this. We have to
special case this like the "==" case.
I discovered this in buildah, since we use the same logic here we should
fix it to prevent unexpected bugs.
> test/helpers.bash: assert handle corner cases correctly

- .cirrus.yml
This is important for the stability of CI in case of a future backport
that happens to be incompatible with netavark `main`.  Since CI
doesn't run very often on the aardvark-dns `v1.0.1-rhel` branch, an
incompatible change may not be noticed.  Fix this by switching off
of the `main` branch onto a netavark release branch.
> Cirrus: Use fixed netavark branch for CI

- src/backend/mod.rs
- src/config/mod.rs
- src/test/config/podman/podman
- src/test/test.rs
As per https://datatracker.ietf.org/doc/html/rfc4343 DNS name resolution
must be case insensitive so convert everything to lowercase by
performing a lookup and storing names into the backend.
Closes: https://github.com/containers/podman/issues/14525
> lookup: make name lookup case insensitive as per `RFC4343`

- aardvark-dns.spec.rpkg
@flouthoc @mheon @baude @Luap99 @rhatdan PTAL
If you have admin/commit access to the `rhcontainerbot/podman-next` copr, this can be tested using: `rpkg copr-build rhcontainerbot/podman-next` . Either way, this change provides successful c8s build, results at: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/4537990/
> CoPR: Fix build for CentOS 8 Stream

- src/backend/mod.rs
- src/config/mod.rs
This gets rids of a small TODO issue, and avoids copying three potentially large HashMaps.
> Move instead of borrow to avoid need to clone

- .cirrus.yml
> Cirrus: remove unused envvar FEDORA_NAME

- .cirrus.yml
Specifically in netavark, a future commit will add native ARM64 builds
and tests there.  However, it needs access to the latest/greatest
ARM64 aardvark-dns builds from a specific $DEST_BRANCH.  Add what's
required to enable that.
> Cirrus: Collect arm binaries for downstream CI

- .github/workflows/check_cirrus_cron.yml
This re-uses the buildah-workflow to send e-mail to podman-monitor if
any Cirrus-cron job failed, or the workflow itself fails.  Necessary to
ensure the CI VM image timestamps are kept updated to prevent pruning.
> GHA: Add Cirrus-cron failure notifications

- Cargo.lock
- Cargo.toml
- RELEASE_NOTES.md
As with Netavark, not on a branch, we can cut one later if required.
> Bump to v1.1.0

- .cirrus.yml
- contrib/cirrus/runner.sh
Other CI systems depend/expect a full set of compiled binaries are
included in the success task's binary artifact (zip file).  However,
it's possible some mistake in CI could silently lead to one or more
binaries not being produced.  For example, a `bin_cache` failure.  Fix
this by verifying all expected/required files are present.  If not,
print the name of the missing binary to assist in
troubleshooting/debugging.
> Cirrus: Verify expected binary artifacts present

- README.md
- config.md
- src/config/mod.rs
- src/test/config/podman_v6_entries/podman_v6_entries_proper
- src/test/test.rs
We have to support several ipv4 and v6 addresses per container. The
current way of creating the configs in aardvark are just broken IMO. We
should never have to duplicate the container id and aliases just to set
more ips.
This patch is fully backwards compatible and will allow much better
config generation in netavark.
> config: use multiple ips per line

- Makefile
This fixes the usage of `[[ ... ]]` since it does not work with `sh`, which `make` uses by default. Using `[ ... ]`/`case ... esac` works fine. 
These changes are similar to https://github.com/containers/netavark/pull/350.
> Fix makefile comparisons

- Makefile
Modify `vendor-rm-windows` to remove windows specific libaries from
vendor directory.
> makefile: remove windows specific libaries from vendor

- Makefile
Modify `vendor-rm-windows` to remove windows specific libaries from
vendor directory
Backport of https://github.com/containers/aardvark-dns/pull/201
@lsm5 @mheon @baude @jnovy PTAL
> [v1.1.0-rhel] makefile: remove windows specific libaries from vendor

- src/commands/run.rs
- src/server/serve.rs
New rule blocks CI since `validation` against clippy is failing hence
remove needless returns from serve and run.
See: https://rust-lang.github.io/rust-clippy/master/index.html#needless_return
> clippy: remove needless returns from code.

- .cirrus.yml
- hack/get_ci_vm.sh
Also, switch to referencing the EC2 AMI by name-tag instead of ID.
> Cirrus: Update meta-task for EC2 image

- Makefile
The vendor tarball generation does not need to check if it's a release
or dev version.
Ref: https://github.com/containers/netavark/pull/401
@mheon @baude @Luap99 @flouthoc PTAL
> Makefile: vendor-tarball remove dev version check

- src/dns/coredns.rs
- test/100-basic-name-resolution.bats
Set recursion available in all response message by setting `RA` flag in
response packet.
Closes: https://github.com/containers/aardvark-dns/issues/204
> coredns: response message always set recursion available (`RA`) when `RD` is set in request

- src/commands/run.rs
- src/server/serve.rs
aardvark-dns must complete writing `pid` in config directory before
parent can return, hence notify parent only after child is done writing
the `pid` file.
> run,serve: create aardvark `pid` in child before we notify parent process

- Cargo.lock
- Cargo.toml
- RELEASE_NOTES.md
* coredns: do not combine results of A and AAAA records
* run,serve: create aardvark pid in child before we notify parent process
* coredns: response message set recursion available if RD is true
* document configuration format
> Release1.2.0

- .cirrus.yml
- Makefile
This Depends on https://github.com/containers/netavark/pull/423 merging and [a branch-build running and passing](https://cirrus-ci.com/github/containers/netavark/v1.1.0-rhel).
> Cirrus: CI branch updates

- build.rs
To make aardvark-dns bit by bit reproducible the embedded build date needs to adhere to the SOURCE_DATE_EPOCH standard. So a rebuilder can set SOURCE_DATE_EPOCH to the build binary's build date and reproduce the binary succesfully.
https://reproducible-builds.org/docs/source-date-epoch/
Signed-off-by: Jelle van der Waa <jelle@archlinux.org>
---
Our reproducible test output before this change: https://reproducible.archlinux.org/api/v0/builds/343291/diffoscope
> Make build date reproducible

- Makefile
The EL rpm specs use a `v` preceeding the version number when looking for the vendor tarballs.
> Add `v` to version in make vendor-tarball

- Cargo.lock
- Cargo.toml
Reduces the features enabled by tokio and futures-util in order to optimize the build process. This currently don't result into any substantial change but it'll improve once downstream crates apply the same optimizations.
> Reduce tokio and futures-util features

- config.md
- contrib/cirrus/setup.sh
- src/backend/mod.rs
- src/config/mod.rs
- src/dns/coredns.rs
- src/test/config/podman_custom_dns_servers/podman
- src/test/test.rs
- test/100-basic-name-resolution.bats
- test/200-two-networks.bats
- test/300-three-networks.bats
- test/400-aliases.bats
- test/500-reverse-lookups.bats
- test/helpers.bash
Aardvark-dns's config now allows containers to define a list of one of more custom `DNS` servers. If custom `DNS` servers are specified for a container aardvark-dns will use these custom DNS servers are resolver instead of host's default revolvers.
* Newly added field to aardvark-dns's config is optional in nature.
- See newly added `integration` and `unit` tests.
- Makes `podman run -it --rm --network test --dns 8.8.8.8 ctr dig google.com` to use `8.8.8.8` as a resolver instead of host's configured resolver.
> aardvark-dns: add support for container's custom `dns_servers`

- Cargo.lock
- Cargo.toml
- build.rs
In order to replace: https://github.com/containers/aardvark-dns/pull/255
> build: bump chrono to `0.4.23` and stop using deprecated `from_timestamp` 

- .github/workflows/rerun_cirrus_cron.yml
Also update the regular cirrus-cron job to reuse the workflow from podman instead of buildah.
> [skip-ci] GHA: Add cirrus-cron auto-rerun job

- .cirrus.yml
- build.rs
- src/server/serve.rs
Bumps the fedora version to 37 and includes a rust update to 1.65.
Fixes the newly reported lint issues as well.
> Ci image update

- Makefile
- docs/publish-crate.md
* Add new rule `make crate-publish` to automate publish at https://crates.io/crates/aardvark-dns
* Document steps for publishing to `crates.io`
> release,make: add rule `crate-publish` for publishing crates.io

- Cargo.toml
- Makefile
See https://github.com/coreos/cargo-vendor-filterer/issues/50 This fixes an error trying to vendor for m68k.
Also while we have the patient open, move the platform list to `Cargo.toml` in declarative format.
Copied as is from https://github.com/containers/netavark/pull/568 by Colin Walters <walters@verbum.org>
> Switch to explicit platform list for `cargo vendor-filterer`

- .packit.sh
- .packit.yaml
- Cargo.toml
This commit will run Koji scratch builds on every PR against all active
releases of Fedora, thus allowing buildability checks before the
PR merges.
> [CI:BUILD] Packit: initial enablement

- src/dns/coredns.rs
Containers can be short lived. We should not allow callers to cache the entry for to long. We could consider turning of cachine all together with a TTL of 0 but 60 seconds seems like a good tradeoff so the clients can still do some caching and not have to request the name every single time.
ref https://github.com/containers/netavark/discussions/644
> use lower TTL for contianer entries

- rpm/aardvark-dns.spec
The lowercase `and` in the License field isn't compatible with spdx license format.
This commit replaces all `and` with `AND` in the License field in spec.
[NO NEW TESTS NEEDED]
> [CI:BUILD] rpm: spdx compatible license field

- Cargo.lock
- Cargo.toml
- src/dns/coredns.rs
vendor: bump `trust_dns_proto` and `trust_dns_client` to `0.23.0`
Closes: https://github.com/containers/aardvark-dns/issues/380
> vendor: bump `trust_dns_proto` and `trust_dns_client` to `0.23.0`

- src/test/test.rs
Output of IpAddr is changed in v`1.72.0` so tests must honor that.
Closes: https://github.com/containers/aardvark-dns/issues/379
> test: IPv6 format is changed in v1.72.0

- Cargo.lock
- Cargo.toml
There are no longer any default features so we need to list explicitly what we use.
> bump nix to 0.27.1

- Cargo.lock
- Cargo.toml
- build.rs
Closes: https://github.com/containers/aardvark-dns/pull/378/files
> cargo: bump chrono to `0.4.30`

- Cargo.lock
- Cargo.toml
- src/dns/coredns.rs
The project got renamed[1]. Update to the first release of hickory. There are no breaking changes so the rename is simple.
[1] https://bluejekyll.github.io/blog/posts/announcing-hickory-dns/
> update trust-dns to hickory

- .packit.yaml
This allows manual submission of a single bodhi update containing netavark and aardvark-dns X.Y builds.
@Luap99 PTAL
Netavark will have a similar PR with additional dep handling in its spec.
> [CI:DOCS] Packit: disable bodhi tasks

- contrib/cirrus/runner.sh
- src/dns/coredns.rs
- test/500-reverse-lookups.bats
- test/helpers.bash
Closes #436 
Hopefully...
I wasn't able to run `aardvark-dns` locally so I wasn't able to test it. Running `RUST_LOG=trace cargo run -- -c src/test/config/podman -p 5533 run` spawns the background process and the pid file is created but I am unable to query it. Any asistance with that would be appreciated.
I also fixed two typos I have noticed along the way.
> Add names for domains in answers in reverse lookups

- Cargo.lock
- Cargo.toml
- src/dns/coredns.rs
- src/server/serve.rs
Instead we parse the new config, replace the in-memory configuration state, stop all old threads for IPs which are no longer in the configuration, and start any new ones for IPs which were added.
Resolves #389.
> Don't tear down all server threads on SIGHUP

- .packit.yaml
- plans/main.fmf
This commit will enable downstream syncing to CentOS Stream 10. The centos maintainer will need to manually run `packit propose-downstream` and `centpkg build` until better centos integration is in place.
This commit will also help to ensure that RHEL tests are run using copr rpms built on rhel (epel) environments, while CentOS Stream tests are run using rpms on centos stream environments.
RHEL-10-Beta tests will need to depend on CentOS Stream 10 rpms until RHEL-10/EPEL-10 copr targets are available.
The `prepare` steps in the TMT tests have been rewritten to be more idiomatic and to account for CentOS Stream 10 / RHEL 10.
> [skip-ci] Packit: enable rhel10, c10s tests and c10s downstream sync

- test/helpers.bash
The test assumed that we have a fdxx:... addresses which is what we should be getting normally, however the ipv6 subnet generator had a bug that caused it to create fdx:... sometimes which is different as ipv6 allows us to omit leading zeros, thus we actually have 0fdx which is not in the range we want to use at all.
So simply fix this by creating the proper subnet so that if the random number was less than 16 we add the leading zero add the proper place after fd.
> fix reverse ipv6 lookup test flake

- .packit.yaml
This should prevent status reporting issues as encountered in https://github.com/containers/aardvark-dns/pull/458 . The possible cause for the error was packit getting confused between two separate copr jobs with the same parameters but different targets.
Having a separate `packages` key for rhel jobs should make it easier for packit to do the right thing.
This should also make it possible for CentOS integration tests to run automatically on all PRs and not need manual triggering by a maintainer. Those were not triggered automatically on
https://github.com/containers/aardvark-dns/pull/456 while the Fedora integration tests were.
> [skip-ci] Packit: separate `packages` key for rhel jobs

- rpm/aardvark-dns.spec
On C9S and RHEL9, we've been specifying our own cargo macro which fails to create debuginfo packages with rust 1.77.2. Ref:
https://blog.rust-lang.org/2024/03/21/Rust-1.77.0.html#enable-strip-in-release-profiles-by-default
This can be remedied by simply using the default __cargo macro provided on build environments.
> [skip-ci] RPM: use default __cargo macro across all envs

- src/backend/mod.rs
- src/config/constants.rs
- src/config/mod.rs
- src/dns/coredns.rs
- test/100-basic-name-resolution.bats
- test/helpers.bash
Internal networks cannot connect to the internet thanks to routing, but they can connect to Aardvark, which will happily forward their DNS requests to the internet.
This could theoretically be used to build a data-exfiltration sidechannel.
Fix this by identifying internal networks with a filename suffix (using a character disallowed in actual network names to ensure we don't conflict with another network) and explicitly setting their DNS servers to an empty list (and refusing to set per-container DNS at all). We could actually error on finding DNS servers in an internal network, but silently ignoring prevents possible compatibility issues with Netavark.
> Internal networks cannot make external DNS requests

- Cargo.lock
- Cargo.toml
- RELEASE_NOTES.md
* Do not allow "internal" networks to access DNS
* On SIGHUP, stop AV threads no longer needed and reload in memory those that are 
* updated dependencies
> Release1.11.0

- rpm/aardvark-dns.spec
The rust-toolset macros in RHEL 10 are now compatible with Fedora's in terms of handling vendoring and automatic generation of license information and bundled provides.
[NO NEW TESTS NEEDED]
> [CI:BUILD] rpm: Update Rust macro usage

- Cargo.lock
- Cargo.toml
- src/commands/run.rs
- src/server/serve.rs
The code currently doesn't check for most child errors as it basicaly
immediately wrote the ready byte. Also it never considered the fact that
the child can exit early and in that case it would have blocked forever
because the parent never closed the writing side before call read().
This fixes that part, however it still reports success way to early. It
should wait for the first bind but that needs more complicated changes.
serve: fix broken error logging
Turns out the task contains a result in a result and we were only
looking at task error caused by tokio and not the actual result returned
from start_dns_server().
This caused all bind error to go nowhere and no even logged by in the
journal.
Fixes: https://github.com/containers/aardvark-dns/commit/224756d98986355d7f7d71d79c8012f0c7e4c29d …
> server: improve parent <-> child error handling 

- Cargo.lock
- Cargo.toml
- src/commands/run.rs
- src/config/mod.rs
- src/dns/coredns.rs
- src/error.rs
- src/lib.rs
- src/main.rs
- src/server/serve.rs
- src/test/test.rs
- test/100-basic-name-resolution.bats
- test/600-errors.bats
- test/helpers.bash
see commits
Listen and forward via tcp as well not just udp
> add tcp support

- contrib/perf/nslookup.py
- contrib/perf/run.sh
Using podman spawn some containers and then check the performance from aardvark-dns.
Comparing results from now after the rework with v1.11 I can see significant gains. While the total time is about the same the new version only uses around 2/3 of the cycles which means cpu utilization is much better now.
> add some basic perf check script

- src/config/mod.rs
- src/test/test.rs
When we list files in directory there is a race where the file might have been removed in the meantime. So ignore the ENOENT case as this is no real error and we still want to parse the other files.
> config: ignore enoent errors while reading configs

- Cargo.toml
To publish our crate, we must use official categories.  In this case, "virtualization" specifically calls out containers and seems appropriate.
Upstream: https://github.com/rust-lang/crates.io/pull/8930
> Change av cargo categories

- src/dns/coredns.rs
Right now for a single network all requests where processed serial and
with tcp a caller is able to block us for a long time if it just opens
the connection but sends very little or no data. To avoid this always
spawn a new task if we accept a new tcp connection.
We could do the same for udp however my testing with contrib/perf/run.sh
has shown that it slows things down as the overhead of spawning a task
is greater than the few quick simple map lookups so we only spawn where
needed. We still have to spawn when forwarding external requests as this
can take a long time.
Fixes #500
> coredns: work on tcp requests concurrently

- .packit.yaml
Packit now supports Fedora sidetags to ship multiple package updates in a single bodhi.
Ref: https://packit.dev/docs/fedora-releases-guide/releasing-multiple-packages
With sidetag enablement, the packit bodhi update job is only needed in
one package. In this case, we can keep the bodhi job in netavark.
Ref: https://github.com/containers/netavark/pull/1071
> [skip-ci] Packit: add sidetag to release with netavark

- Cargo.lock
- Cargo.toml
- src/dns/coredns.rs
- src/server/serve.rs
Instead we parse the new config, replace the in-memory configuration state, stop all old threads for IPs which are no longer in the configuration, and start any new ones for IPs which were added.
Paul:
Fixing merge conflicts in Cargo.toml and bumping time because that no longer builds on rust v1.80
Fixes https://issues.redhat.com/browse/RHEL-59129
Fixes https://issues.redhat.com/browse/ACCELFIX-287
> [v1.10.0-rhel] Don't tear down all server threads on SIGHUP

- Cargo.lock
- Cargo.toml
New rhel release for
https://issues.redhat.com/browse/RHEL-59129
https://issues.redhat.com/browse/ACCELFIX-287
Also fix the cargo categories in case we want to push to crates.io.
> Release v1.10.1-rhel

- Cargo.lock
- Cargo.toml
- src/dns/coredns.rs
- src/error.rs
- src/server/serve.rs
The resolv.conf parsing lib is super strict and does not allow unknown options, given we do not care about options search domains or really anything else in this file parse it ourselves with very lax rules.
Basically we try to find the nameserver lines. Anything else is ignored, the only error we produce is if we fail to parse the nameserver ip address.
Fixes #418
Fixes https://issues.redhat.com/browse/RHEL-57695
> serve: parse resolv.conf ourselves

- .packit.yaml
We have disabled Fedora 39 on podman-next copr. So, it's best to disable build and tests for them here too.
This commit also separates out ELN jobs into a separate set using `packages: [aardvark-dns-eln]` key-value.
YAML anchors are also used for reusing fedora and centos stream targets for upstream and downstream jobs.
> Packit: disable F39 and separate out ELN

- src/server/serve.rs
- test/100-basic-name-resolution.bats
The dig version there doesn't print the protocol in the output and it is not really that important to check as we assume that dig +tcp does the right thing anyway.
> test: make them pass on RHEL/Centos Stream 9

- src/backend/mod.rs
- src/dns/coredns.rs
- src/test/test.rs
- test/200-two-networks.bats
In my rework it seems I broke the weird way how we tried to resolve
names when we have no source ip match. Let's do this properly and move
the logic all into lookup() which makes it much cleaner and no
duplication needed.
Now there is catch here, we only lookup the network for the current
network listener, so if the user has multiple networks they always must
target the requests against the correct ip depeding on what network the
name is in. But this is the same as it worked before and seems safer
than allowing a unknown ip to access all names I guess.
Fixes https://github.com/containers/aardvark-dns/issues/508
> coredns: allow host lookup of names

- src/dns/coredns.rs
- test/100-basic-name-resolution.bats
- test/500-reverse-lookups.bats
Containers can be be restarted with a different ip at any time so
allowing caches here doesn't make much sense given the server is local
and queries should be fast enough anyway.
Fixes https://github.com/containers/aardvark-dns/issues/429
> coredns: use a TTL of 0 for our names

- src/dns/coredns.rs
- src/server/serve.rs
- test/100-basic-name-resolution.bats
The default timeout was 5s and as 5s is the default for most clients we may try more upstream servers but at that point the client already considered this a timeout and no longer accepts answers. As such if we want to try more reolvers in case the first one is offline/not working then we need a lower timeout. Let's only try 3 as glibc does and then just divide 5s through the number of resolvers, i.e. 1, 2, 3. This should make the fall back work.
Fixes #482
> dns: limit to 3 resolvers and use better timeout for them

- .packit.yaml
This helps to avoid dup downstream jobs. Doesn't affect upstream.
> [skip-ci] Packit: constrain koji job to the fedora package

- .cirrus.yml
- README.md
like in https://github.com/containers/netavark/pull/1098
> define a msrv policy

- src/dns/coredns.rs
- test/100-basic-name-resolution.bats
- test/200-two-networks.bats
- test/300-three-networks.bats
- test/dnsmasq.conf
- test/helpers.bash
Docker does this and there might be local names and a local resolver that otherwise cannot be resolved.
Fixes https://issues.redhat.com/browse/RHEL-61873
> coredns: forward names with no ndots as well

- Cargo.lock
- Cargo.toml
- RELEASE_NOTES.md
* Set TTL to 0 for container names
* Allow forwarding of names with no ndots
* DNS: limit to 3 resolvers and use better timeout for them
* Ignore unknown resolv.conf options
> Release v1.13.0

- Cargo.lock
- Cargo.toml
- src/dns/coredns.rs
- src/server/serve.rs
- test/100-basic-name-resolution.bats
The recent change to move parsing resolv.conf into our code caused a regression with link local addresses. We did not split "%" correctly due a typo. While the fix for that is simple ignoring the zone part as we did before will not work as the zone must be given for link local addresses.
And as it turns out it does not need much changes to actually support the zone part properly. We can just pass the SocketAddr type around. The only problem there is that we must know the numeric id and not the interface name in the struct. To resolve name -> id we can simply call if_nametoindex that is provided by libc which is safely wrapped in the nix crate.
Fixes 22293ef ("serve: parse resolv.conf ourselves")
Fixes #535
> support ipv6 link local addresses in resolv.conf

- .packit.yaml
- plans/main.fmf
- rpm/aardvark-dns.spec
This PR:
1. enables c9s downstream update via packit
2. cleans up changelog conditionals from rpm spec
3. installs builddeps in downstream testing-farm environments (needed to run rpmbuild -bp).
> [skip-ci] Packit / TMT / rpm update (see individual commits)

- Cargo.lock
- Cargo.toml
rust 1.83 starts to upgrade the Cargo.lock version field to version 4,
however version 4 support was only added in 1.78 which is newer than our
MSRV 1.76. To ensure cargo respects the MSRV we need to set in the in
Cargo.toml.
And also some dep updates from renovate so I don't have to rebase all the PRs
> cargo: set rust-version 

- test/helpers.bash
We don't care about the driver used for out testing so just stick with the package default. I did add this only to get passing test locally back then and didn't actually intend to commit this at all.
> test: do not force nftables

- .packit.yaml
- plans/main.fmf
- rpm/aardvark-dns.spec
- rpm/gating.yaml
- test/tmt/main.fmf
- test/tmt/test_integration.sh
This makes fetching and running of gating tests similar to podman, buildah and skopeo.
> [skip-ci] RPM/TMT: use tests subpackage

- CONTRIBUTING.md
- README.md
This PR adds a link to c/common contributor's guide. 
Fixes: https://issues.redhat.com/browse/RUN-2321
Note: After the merge https://github.com/containers/common/pull/2386, the contributor's guide will contain sections specific to Golang and Rust.
> Add link to c/common contributor's guide

- .cirrus.yml
- Makefile
- hack/tree_status.sh
ci: ensure tree is clean after build
To ensure Cargo.lock or other files that are committed are not modified
by the build in CI.
---
Makefile: use cargo --locked in CI
CI should never modify the lockfile so add --locked when running under
CI, the CI env is always defined by cirrus.
https://doc.rust-lang.org/cargo/commands/cargo.html#manifest-options
(like the netavark PR https://github.com/containers/netavark/pull/1233)
> ci: ensure build does not modify committed files

- Cargo.lock
- Cargo.toml
- src/commands/run.rs
- src/server/serve.rs
The dup2 API has changed and now requires an OwnedFd as traget fd, that is not what we have or want. An OwnedFd is closed on drop so even if I would create one it would be dropped at the end of the function which would then close stdin/out/err which would be clearly wrong.
To accommodate the common use case of replacing the std stream nix added the dup2_stdin/stdout/stderr functions instead which we now use.
Also read no longer accepts a raw fd either.
> deps: update nix to 0.30.1

- .gitignore
- Makefile
The make target like done in netavark should put the files into the vendor-tarball directory.
Fixes: ce41695 ("github: add automatic release action")
> fix github release action
